# Generated by Django 2.2 on 2019-04-16 00:22

from django.db import migrations, models
import skynet_resources.models.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(max_length=150)),
                ('_type', models.IntegerField(choices=[(1, skynet_resources.models.enums.DeviceType(1))])),
                ('_port_number', models.IntegerField()),
                ('_created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(max_length=100)),
                ('_type', models.IntegerField(choices=[(1, skynet_resources.models.enums.RoomType(1)), (2, skynet_resources.models.enums.RoomType(2)), (3, skynet_resources.models.enums.RoomType(3))])),
                ('_created_date', models.DateTimeField(auto_now_add=True)),
                ('_devices', models.ManyToManyField(to='skynet_resources.Device')),
            ],
        ),
    ]
